---
- name: Configure Feature
  hosts: all
  connection: network_cli
  tasks:
    - name: Configure Feature User via j2 template
      nxos_config:
         src: "../templates/feature.j2"
         save_when: changed
      notify: config_changed
      register: cli_result
  
  handlers:
    - name: "HANDLER 1: Display changes"
      listen: config_changed
      debug: 
        msg: "{{ cli_result.commands }}"

