---
- name: "PLAY 1: TEST SNMP"
  hosts: all
  connection: local
  tasks:
    - name: "TEST FACTS"
      snmp_facts:
        host: "{{ ansible_host }}" 
        version: v3
        level: authPriv
        integrity: sha
        privacy: aes
        username: "{{ item.user }}"
        authkey: "{{ item.pwd }}"
        privkey: "{{ item.privacy }}"
      with_items: "{{ snmp_users }}"
      delegate_to: localhost
      notify: snmp_facts_collected

  handlers: 
    - name: "darts"
      listen: snmp_facts_collected
      fail: 
        msg: parse err
      when: '"Xisco NX-OS" not in "{{ ansible_architecture }}"' 
