---
- name: "PLAY 1: CONFIGURE SNMPv3"
  hosts: all
  connection: network_cli
  tasks:
    - name: "TASK 1: CONFIGURE SNMP VIA J2 TEMPLATE"
      nxos_config:
         src: "../templates/snmp.j2"
         save_when: changed
      notify: config_changed
      register: cli_result

  handlers:
    - name: "HANDLER 1: DISPLAY GENERATED CONFIGURATION"
      listen: config_changed
      debug:
        msg: "{{ cli_result.commands }}"

